server {
  listen 80;
  listen [::]:80;
  server_name www.trtst.com;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name www.trtst.com;

  root /srv/cook/apps/site/dist;
  index index.html;

  ssl_certificate /etc/letsencrypt/live/www.trtst.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.trtst.com/privkey.pem;

  location /assets/ {
    try_files $uri =404;
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800, immutable";
  }

  location = /favicon.ico {
    try_files $uri =404;
    access_log off;
    expires 1d;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

server {
  listen 80;
  listen [::]:80;
  server_name trtst.com;

  return 301 https://www.trtst.com$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name trtst.com;

  ssl_certificate /etc/letsencrypt/live/www.trtst.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/www.trtst.com/privkey.pem;

  return 301 https://www.trtst.com$request_uri;
}
